### ISSUE TITLE
Module 별 PDF 파일 분석 후 계획 세우기

### ISSUE THREAD

**Issue by brixxt27** [brixxt27/cpp_module#1]
## TODO
### module 별 pdf를 시작 전 모두 가볍게 읽으면서 키워드 분석하기
- [x] 00
- [x] 01
- [x] 02
- [x] 03
- [x] 04
- [x] 05
- [x] 06
- [x] 07
- [x] 08
### 인강
- [x] pocu academy C++ 언매니지드 프로그래밍 인강 어떻게 들을지 계획 세우기
### 계획
- [x] 어떤 식으로 과제를 진행해 갈지 계획 세우기
### 강의 진행도
- [x] 1~9, 11, 12  까지 완료
- [x] 10은 casting 이라서 C++ module 06 할 때 보기 위해 남겨둠.
- [x] 13은 Exception 이라 C++ module 05 할 때 보면 됨
- [ ] 14 15 16 18 은 STL(표준 템플릿 라이브러리) 사용법 및 관련 내용이라 C++ module 08에서 볼 예정
- [ ] 17 은 템플릿 프로그래밍이므로 C++ module 07에서 볼 예정

**Comment by brixxt27** [comment]
인강 계획 cpp04까지 세웠다. 05가 예외이고, 06이 캐스팅이어서 인강 순서를 조금 다르게 봐야할 것 같다. 중간에 인라인 함수, static키워드 등이 있어서 이건 과제와 상관 없이 보면 좋을 영상으로 보인다.
